<a href="https://colab.research.google.com/github/zhaoheng001/colabtogithubdemo/blob/master/Backward_dynamic_programming%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import math
import numpy as np


Prob_fail = np.array([[0.80,0.75,0.90], 
              [0.70,0.70,0.70], 
              [0.65,0.67,0.60], 
              [0.62,0.65,0.55], 
              [0.60,0.62,0.50]])
assign_time = np.zeros(3)
T = 4

#stage1
p3 = Prob_fail[:, 2]
p2 = Prob_fail[:, 1]
p1 = Prob_fail[:, 0]

#stage2
f3 = np.zeros(T+1)
f3 = p3
f2 = np.zeros(T+1)
f2_index = np.zeros(T+1)
f1 = np.zeros(0)
f1_index = np.zeros(0)

f2_index_0 = np.zeros(T+1)
for i in range(T+1):
  temp1 = np.zeros(i+1)
  for t1 in range(i+1):
    temp = p2[t1]*f3[i-t1]
    temp1[t1] = temp
  f2[i] = min(temp1)
  f2_index[i] = np.argmin(temp1)
  f2_index_0[i] = i - f2_index[i]
  print('\n')
  print(f2[i])
  print(f2_index[i])
print(f2_index_0)
print(f2_index)
print('\n')

#stage3
temp2 = np.zeros(T+1)
for j in range(T+1):
  temp2[j] = p1[j]*f2[T-j]
  #print(temp2[j]) 
f1 = min(temp2)
f1_index = np.argmin(temp2)


assign_time[0] = f1_index
assign_time[1] = f2_index[T-f1_index]
assign_time[2] = f2_index_0[T-f1_index] - assign_time[1]
print('\n')
print(f1)
print(f1_index)
print(assign_time)



print('\n')
print('\n')

print("Optimal policy:")
print(assign_time[0], "day on course 1")
print(assign_time[1], "day on course 2")
print(assign_time[2], "day on course 3")





0.675
0.0


0.5249999999999999
0.0


0.44999999999999996
0.0


0.41250000000000003
0.0


0.375
0.0
[0. 1. 2. 3. 4.]
[0. 0. 0. 0. 0.]




0.28875
1
[1. 0. 3.]




Optimal policy:
1.0 day on course 1
0.0 day on course 2
3.0 day on course 3
